<?php

namespace App\Services;

use InvalidArgumentException;

/**
 * ALGORITHMIC AURAL EXERCISE GENERATOR
 * =====================================
 * One method per Aural module (1A-1D). Each method procedurally builds a fresh
 * exercise + its answer key, so every attempt is a new variation instead of
 * pulling from a fixed question bank (unlike the Theory quizzes).
 *
 * Only Grade 1's rules are implemented right now. Every method throws for any
 * other grade level rather than silently returning something wrong - Grades
 * 2-5 need their own ABRSM-style rules defined before we can generate for them.
 */
class AuralExerciseGeneratorService
{
    // The 12 chromatic pitch names, used as a lookup table when converting a
    // "scale degree" number into an actual note name (e.g. degree 2 in C major = "E").
    private const CHROMATIC_NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

    // Semitone distance of each of the 7 major-scale degrees above the tonic
    // (the classic "whole-whole-half-whole-whole-whole-half" pattern).
    private const MAJOR_SCALE_SEMITONES = [0, 2, 4, 5, 7, 9, 11];

    // Grade 1 ABRSM-style constraint: only these four "easy" major keys are used.
    private const GRADE_1_KEYS = ['C', 'G', 'D', 'F'];

    /**
     * Maps a Pulse & Metre session's question_number (1-10) onto its phase:
     * 1-3 pure listening MCQ, 4-6 downbeat-only tapping, 7-9 tap-through-silence,
     * 10 the combined "boss" question. Static (and public) because both
     * AuralModuleController and PulseMetreAuthoredQuestionSeeder need this
     * exact same mapping - the seeder uses it to validate that an authored
     * question's declared phase actually matches its question_number.
     */
    public static function phaseForQuestionNumber(int $questionNumber): string
    {
        return match (true) {
            $questionNumber <= 3 => 'listen_mcq',
            $questionNumber <= 6 => 'downbeat_tap',
            $questionNumber <= 9 => 'muted_bar_tap',
            default => 'boss',
        };
    }

    /**
     * 1A: PULSE & METRE
     * A 4-phase, 10-question progression (see phaseForQuestionNumber() above
     * for how question number maps to phase):
     *   - listen_mcq (Q1-3): hear a real 2-bar clip, answer "2 time or 3 time?" -
     *     generated by AuralModuleController::generateListenClipPayload() instead
     *     of here, since it needs to pick a clip from PulseMetreClip, not
     *     synthesize a beat grid. Reaching this method with that phase is a bug.
     *   - downbeat_tap (Q4-6): tap only on the strong beat (beat 1 of each bar)
     *   - muted_bar_tap (Q7-9): bar 1 audible, bar 2 silent - tap through the silence
     *   - boss (Q10): muted_bar_tap + the listen_mcq question, both must be correct
     */
    public function generatePulseMetre(int $gradeLevel, string $phase): array
    {
        $this->assertGradeOneOnly($gradeLevel, 'Pulse & Metre');

        [$tempoBpm, $timeSignature, $beatsPerBar, $bars, $beatTimestampsMs] = $this->buildBeatGrid();

        $payload = [
            'module_type' => 'pulse_metre',
            'phase' => $phase,
            'tempo_bpm' => $tempoBpm,
            'time_signature' => $timeSignature,
            'beats_per_bar' => $beatsPerBar,
            'bars' => $bars,
            // The client plays a click/loop at these exact millisecond offsets and
            // captures the user's tap timestamps to compare against them later.
            'beat_timestamps_ms' => $beatTimestampsMs,
            // Only used server-side by submitAttempt() to grade the follow-up MCQ.
            'ground_truth' => [
                'time_signature' => $timeSignature,
            ],
        ];

        return match ($phase) {
            'downbeat_tap' => array_merge($payload, $this->downbeatTapFields($beatTimestampsMs, $beatsPerBar)),
            'muted_bar_tap' => array_merge($payload, $this->mutedBarTapFields($beatsPerBar)),
            'boss' => array_merge($payload, $this->mutedBarTapFields($beatsPerBar), $this->listenMcqFields()),
            default => throw new InvalidArgumentException("Unknown Pulse & Metre phase: {$phase}"),
        };
    }

    /**
     * Shared beat grid (tempo, time signature, beat timestamps) used by every
     * Pulse & Metre phase - only the question/interaction wrapped around it differs.
     */
    private function buildBeatGrid(): array
    {
        $tempoBpm = random_int(60, 100);
        $timeSignature = random_int(0, 1) === 0 ? '2/4' : '3/4';
        $beatsPerBar = $timeSignature === '2/4' ? 2 : 3;
        $bars = 2;
        $totalBeats = $beatsPerBar * $bars;

        // How many milliseconds separate each beat at this tempo.
        $beatIntervalMs = (int) round(60000 / $tempoBpm);

        // Small lead-in before the first beat so the user has time to get ready to tap.
        $leadInMs = 500;
        $beatTimestampsMs = [];
        for ($i = 0; $i < $totalBeats; $i++) {
            $beatTimestampsMs[] = $leadInMs + ($i * $beatIntervalMs);
        }

        return [$tempoBpm, $timeSignature, $beatsPerBar, $bars, $beatTimestampsMs];
    }

    /**
     * The "2 time or 3 time?" question, with archetype labels (March/Waltz)
     * alongside the raw option values so the client can render two labeled
     * buttons without hardcoding the mapping itself. Public because both the
     * `boss` phase here and AuralModuleController::generateListenClipPayload()
     * (the real-clip listen_mcq phase) need this exact same MCQ shape.
     */
    public function listenMcqFields(): array
    {
        return [
            'question' => [
                'prompt' => 'Was the music in 2 time or 3 time?',
                'options' => ['2/4', '3/4'],
                'option_labels' => [
                    '2/4' => 'March 🚶',
                    '3/4' => 'Waltz 💃',
                ],
            ],
        ];
    }

    /**
     * downbeat_tap phase fields: which beat indices are "beat 1" of a bar. Not
     * answer-leaking - the client needs these anyway to sound a distinct downbeat
     * timbre (e.g. woodblock vs clave), same as it already needs every timestamp
     * to play the click track at all. Public because
     * AuralModuleController::buildAuthoredPulseMetrePayload() reuses this same
     * index math for authored questions instead of re-deriving it.
     */
    public function downbeatTapFields(array $beatTimestampsMs, int $beatsPerBar): array
    {
        $downbeatIndices = [];
        for ($i = 0; $i < count($beatTimestampsMs); $i += $beatsPerBar) {
            $downbeatIndices[] = $i;
        }

        return [
            'downbeat_indices' => $downbeatIndices,
            'instruction' => 'Tap only on the strong beat (Beat 1 of each bar).',
        ];
    }

    /**
     * muted_bar_tap phase fields: which beat indices are actually sounded (bar 1
     * only) - bar 2's timestamps stay in beat_timestamps_ms for grading, but the
     * client goes silent for them so the user must tap through from memory.
     * Public for the same reason as downbeatTapFields() above.
     */
    public function mutedBarTapFields(int $beatsPerBar): array
    {
        return [
            'audible_beat_indices' => range(0, $beatsPerBar - 1),
            'instruction' => 'Keep tapping the beat through the silent second bar.',
        ];
    }

    /**
     * 1B: ECHO SINGING
     * Generates the 2-bar melodic phrase the user must sing back. The DSP scoring
     * for this module isn't implemented yet (see AuralModuleController::submitAttempt),
     * but the exercise shape is defined now so the client has something to play.
     */
    public function generateEchoPhrase(int $gradeLevel): array
    {
        $this->assertGradeOneOnly($gradeLevel, 'Echo Singing');

        $key = self::GRADE_1_KEYS[array_rand(self::GRADE_1_KEYS)];

        // Grade 1 rule: 2 bars of 4/4, melody never leaps more than a 3rd
        // (i.e. never moves more than 2 scale degrees) between consecutive notes.
        $noteSequence = $this->generateStepwiseMelody($key, beatsBudget: 8.0, maxDegreeStep: 2);

        return [
            'module_type' => 'echo_singing',
            'key' => $key,
            'bars' => 2,
            'note_sequence' => $noteSequence,
            'ground_truth' => [
                // Kept for when real phrase-matching DSP is wired up later.
                'note_sequence' => $noteSequence,
            ],
        ];
    }

    /**
     * 1C: SPOTTING THE DIFFERENCE
     * Plays the same short melody twice, but the second playback has one note's
     * pitch altered near either the beginning or the end. User picks which.
     */
    public function generateSpotDifference(int $gradeLevel): array
    {
        $this->assertGradeOneOnly($gradeLevel, 'Spotting the Difference');

        $key = self::GRADE_1_KEYS[array_rand(self::GRADE_1_KEYS)];
        $originalSequence = $this->generateStepwiseMelody($key, beatsBudget: 4.0, maxDegreeStep: 2);
        $noteCount = count($originalSequence);

        // Split the sequence into thirds and pick the changed note from either the
        // first or last third, so "beginning" vs "end" is always unambiguous.
        $thirdSize = max(1, (int) floor($noteCount / 3));
        $changeNearBeginning = random_int(0, 1) === 0;

        if ($changeNearBeginning) {
            $changedIndex = random_int(0, $thirdSize - 1);
            $position = 'beginning';
        } else {
            $changedIndex = random_int($noteCount - $thirdSize, $noteCount - 1);
            $position = 'end';
        }

        $alteredSequence = $originalSequence;
        $originalNote = $originalSequence[$changedIndex];

        // Shift the chosen note by 1-2 scale degrees (up or down) so it's audibly
        // different but still diatonic - re-roll if it happens to land unchanged.
        do {
            $shift = random_int(1, 2) * (random_int(0, 1) === 0 ? -1 : 1);
            $alteredNote = $this->degreeToNote($key, $originalNote['degree'] + $shift, $originalNote['octave_offset']);
        } while ($alteredNote['note_name'] === $originalNote['note_name']);

        $alteredSequence[$changedIndex] = array_merge($alteredNote, ['duration_beats' => $originalNote['duration_beats']]);

        return [
            'module_type' => 'spot_difference',
            'key' => $key,
            'original_sequence' => $originalSequence,
            'altered_sequence' => $alteredSequence,
            'question' => [
                'prompt' => 'Did the change happen near the Beginning or the End?',
                'options' => ['beginning', 'end'],
            ],
            'ground_truth' => [
                'changed_index' => $changedIndex,
                'position' => $position,
            ],
        ];
    }

    /**
     * 1D: MUSICAL FEATURES
     * Generates a short phrase performed with a specific dynamic (forte/piano)
     * and articulation (legato/staccato); user identifies both.
     */
    public function generateMusicalFeatures(int $gradeLevel): array
    {
        $this->assertGradeOneOnly($gradeLevel, 'Musical Features');

        $key = self::GRADE_1_KEYS[array_rand(self::GRADE_1_KEYS)];
        $dynamic = random_int(0, 1) === 0 ? 'forte' : 'piano';
        $articulation = random_int(0, 1) === 0 ? 'legato' : 'staccato';
        $noteSequence = $this->generateStepwiseMelody($key, beatsBudget: 4.0, maxDegreeStep: 2);

        return [
            'module_type' => 'musical_features',
            'key' => $key,
            'note_sequence' => $noteSequence,
            // Client-renderable playback hints - not the answer itself, just how loud/
            // connected to play the notes so it actually sounds forte/piano, legato/staccato.
            'dynamic_hint' => [
                'velocity' => $dynamic === 'forte' ? 100 : 40, // MIDI-style 0-127 loudness
            ],
            'articulation_hint' => [
                // Fraction of each note's written duration that actually sounds before
                // a rest (legato notes ring almost fully; staccato notes are clipped short).
                'duration_multiplier' => $articulation === 'legato' ? 0.95 : 0.5,
            ],
            'question' => [
                'dynamic' => [
                    'prompt' => 'Was the piece loud (Forte) or quiet (Piano)?',
                    'options' => ['forte', 'piano'],
                ],
                'articulation' => [
                    'prompt' => 'Was the piece smooth (Legato) or short and detached (Staccato)?',
                    'options' => ['legato', 'staccato'],
                ],
            ],
            'ground_truth' => [
                'dynamic' => $dynamic,
                'articulation' => $articulation,
            ],
        ];
    }

    /**
     * TRANSCRIPTION (adaptive-sequencing gated; Gordon MLT symbolic-association
     * stage). A short 4-6 note stepwise pattern the user must notate after
     * hearing it - intentionally brief, not a full melody, matching Gordon
     * MLT's short tonal/rhythm pattern approach rather than long-phrase
     * dictation. Ground truth is embedded in the payload the same way every
     * other module here does it (see aural_exercises migration) - not new
     * hiding logic, just the existing convention.
     */
    public function generateTranscription(int $gradeLevel): array
    {
        $this->assertGradeOneOnly($gradeLevel, 'Transcription');

        $key = self::GRADE_1_KEYS[array_rand(self::GRADE_1_KEYS)];
        $noteSequence = $this->generateStepwiseMelody($key, beatsBudget: 4.0, maxDegreeStep: 2);

        return [
            'module_type' => 'transcription',
            'key' => $key,
            'note_sequence' => $noteSequence,
            'ground_truth' => [
                'note_sequence' => $noteSequence,
            ],
        ];
    }

    /**
     * Shared melody generator used by 1B/1C/1D/Transcription: a random-walk over scale degrees
     * (never stepping more than $maxDegreeStep degrees at a time, which is what
     * keeps every leap within a 3rd), with random quarter/eighth-note rhythms
     * filling up the given beat budget.
     */
    private function generateStepwiseMelody(string $key, float $beatsBudget, int $maxDegreeStep): array
    {
        $notes = [];
        $currentDegree = 0; // Start on the tonic.
        $beatsUsed = 0.0;

        while ($beatsUsed < $beatsBudget) {
            $remaining = $beatsBudget - $beatsUsed;
            // Pick a quarter (1 beat) or eighth (0.5 beat) note, but never overshoot the budget.
            $duration = ($remaining >= 1.0 && random_int(0, 1) === 0) ? 1.0 : min(0.5, $remaining);

            $note = $this->degreeToNote($key, $currentDegree);
            $notes[] = array_merge($note, ['duration_beats' => $duration]);

            $beatsUsed += $duration;

            // Walk to the next degree, keeping the melody within a compact,
            // beginner-singable range (roughly a 6th either side of the tonic) -
            // a plain random walk with no bound would happily wander a full
            // octave away over just a handful of notes.
            $step = random_int(-$maxDegreeStep, $maxDegreeStep);
            $currentDegree = max(-4, min(4, $currentDegree + $step));
        }

        return $notes;
    }

    /**
     * Converts a scale-degree number (0 = tonic, can be negative or > 6 to move
     * into neighbouring octaves) into a concrete note name + octave, e.g.
     * degreeToNote('C', 2) => ['note_name' => 'E', 'octave' => 4, ...].
     */
    private function degreeToNote(string $key, int $degree, int $octaveOffset = 4): array
    {
        $rootIndex = array_search($key, self::CHROMATIC_NOTES, true);

        // Split the degree into "which octave" and "which of the 7 degrees within it",
        // handling negative degrees correctly (PHP's % can return negative results).
        $octaveShift = (int) floor($degree / 7);
        $degreeInOctave = $degree - ($octaveShift * 7);

        $semitoneOffset = self::MAJOR_SCALE_SEMITONES[$degreeInOctave] + ($octaveShift * 12);
        $absoluteSemitone = ($octaveOffset * 12) + $rootIndex + $semitoneOffset;

        $octave = intdiv($absoluteSemitone, 12);
        $noteIndex = $absoluteSemitone % 12;

        return [
            'note_name' => self::CHROMATIC_NOTES[$noteIndex],
            'octave' => $octave,
            'degree' => $degree,
            'octave_offset' => $octaveOffset,
        ];
    }

    private function assertGradeOneOnly(int $gradeLevel, string $moduleName): void
    {
        if ($gradeLevel !== 1) {
            throw new InvalidArgumentException(
                "{$moduleName} exercise generation is not yet implemented for Grade {$gradeLevel} - only Grade 1's rules exist so far."
            );
        }
    }
}
